# Generated by Django 5.1.4 on 2024-12-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Optional. Image file.",
                null=True,
                upload_to="users/avatars/",
                verbose_name="avatar",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="telegram chat id"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="tg_nick",
            field=models.CharField(
                blank=True,
                help_text="Required. 50 characters or fewer. Letters, digits and _ only.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="telegram nickname",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="estimated_time",
            field=models.PositiveIntegerField(help_text="Время в секундах"),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remind_at", models.DateTimeField()),
                ("message", models.CharField(max_length=255)),
                ("sent", models.BooleanField(default=False)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="habits.habit"
                    ),
                ),
            ],
        ),
    ]
